package screens.settings

val listSettings = listOf<String>(
    "android.settings.SETTINGS",
    "android.settings.APN_SETTINGS",
    "android.settings.LOCATION_SOURCE_SETTINGS",
    "android.settings.LOCATION_CONTROLLER_EXTRA_PACKAGE_SETTINGS",
    "android.settings.LOCATION_SCANNING_SETTINGS",
    "android.settings.MANAGE_CLONED_APPS_SETTINGS",
    "android.settings.USER_SETTINGS",
    "android.settings.WIRELESS_SETTINGS",
    "android.settings.TETHER_PROVISIONING_UI",
    "android.settings.TETHER_UNSUPPORTED_CARRIER_UI",
    "android.settings.AIRPLANE_MODE_SETTINGS",
    "android.settings.MOBILE_DATA_USAGE",
    "android.settings.action.ONE_HANDED_SETTINGS",
    "android.settings.VOICE_CONTROL_AIRPLANE_MODE",
    "android.settings.ACCESSIBILITY_SETTINGS",
    "android.settings.ACCESSIBILITY_DETAILS_SETTINGS",
    "android.settings.ACCESSIBILITY_COLOR_MOTION_SETTINGS",
    "android.settings.REDUCE_BRIGHT_COLORS_SETTINGS",
    "com.android.settings.ACCESSIBILITY_COLOR_SPACE_SETTINGS",
    "android.settings.COLOR_INVERSION_SETTINGS",
    "android.settings.TEXT_READING_SETTINGS",
    "android.settings.USAGE_ACCESS_SETTINGS",
    "android.intent.category.USAGE_ACCESS_CONFIG",
    "android.settings.metadata.USAGE_ACCESS_REASON",
    "android.settings.SECURITY_SETTINGS",
    "android.settings.MANAGE_UNKNOWN_APP_SOURCES",
    "android.settings.REQUEST_SCHEDULE_EXACT_ALARM",
    "android.settings.REQUEST_MANAGE_MEDIA",
    "android.settings.MANAGE_APP_LONG_RUNNING_JOBS",
    "android.settings.MANAGE_CROSS_PROFILE_ACCESS",
    "android.settings.APP_OPEN_BY_DEFAULT_SETTINGS",
    "com.android.settings.TRUSTED_CREDENTIALS_USER",
    "com.android.settings.MONITORING_CERT_INFO",
    "android.settings.PRIVACY_SETTINGS",
    "android.settings.VPN_SETTINGS",
    "android.settings.WIFI_SETTINGS",
    "android.settings.ADVANCED_MEMORY_PROTECTION_SETTINGS",
    "android.settings.WIFI_IP_SETTINGS",
    "android.settings.PROCESS_WIFI_EASY_CONNECT_URI",
    "android.settings.DATA_USAGE_SETTINGS",
    "android.settings.BLUETOOTH_SETTINGS",
    "android.settings.APP_SEARCH_SETTINGS",
    "android.settings.ASSIST_GESTURE_SETTINGS",
    "android.settings.FINGERPRINT_ENROLL",
    "android.settings.BIOMETRIC_ENROLL",
    "android.settings.CAST_SETTINGS",
    "android.settings.DATE_SETTINGS",
    "android.settings.SOUND_SETTINGS",
    "android.settings.DISPLAY_SETTINGS",
    "android.settings.AUTO_ROTATE_SETTINGS",
    "android.settings.NIGHT_DISPLAY_SETTINGS",
    "android.settings.DARK_THEME_SETTINGS",
    "android.settings.LOCALE_SETTINGS",
    "android.settings.APP_LOCALE_SETTINGS",
    "android.settings.REGIONAL_PREFERENCES_SETTINGS",
    "android.settings.LOCK_SCREEN_SETTINGS",
    "android.settings.BLUETOOTH_PAIRING_SETTINGS",
    "android.settings.VOICE_INPUT_SETTINGS",
    "android.settings.INPUT_METHOD_SETTINGS",
    "android.settings.INPUT_METHOD_SUBTYPE_SETTINGS",
    "android.settings.USER_DICTIONARY_SETTINGS",
    "android.settings.HARD_KEYBOARD_SETTINGS",
    "com.android.settings.USER_DICTIONARY_INSERT",
    "android.settings.APPLICATION_SETTINGS",
    "android.settings.APPLICATION_DEVELOPMENT_SETTINGS",
    "android.settings.QUICK_LAUNCH_SETTINGS",
    "android.settings.MANAGE_APPLICATIONS_SETTINGS",
    "android.settings.MANAGE_ALL_APPLICATIONS_SETTINGS",
    "android.settings.MANAGE_ALL_SIM_PROFILES_SETTINGS",
    "android.settings.action.MANAGE_OVERLAY_PERMISSION",
    "android.settings.MANAGE_APP_OVERLAY_PERMISSION",
    "android.settings.action.MANAGE_WRITE_SETTINGS",
    "android.settings.action.APP_USAGE_SETTINGS",
    "android.settings.APPLICATION_DETAILS_SETTINGS",
    "android.settings.FOREGROUND_SERVICES_SETTINGS",
    "android.settings.IGNORE_BATTERY_OPTIMIZATION_SETTINGS",
    "android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS",
    "android.settings.VIEW_ADVANCED_POWER_USAGE_DETAIL",
    "android.settings.IGNORE_BACKGROUND_DATA_RESTRICTIONS_SETTINGS",
    "android.settings.APP_OPS_SETTINGS",
    "android.settings.SYSTEM_UPDATE_SETTINGS",
    "android.settings.MANAGED_PROFILE_SETTINGS",
    "android.settings.SYNC_SETTINGS",
    "android.settings.ADD_ACCOUNT_SETTINGS",
    "android.settings.DATA_SAVER_SETTINGS",
    "android.settings.NETWORK_OPERATOR_SETTINGS",
    "android.settings.DATA_ROAMING_SETTINGS",
    "android.settings.INTERNAL_STORAGE_SETTINGS",
    "android.settings.MEMORY_CARD_SETTINGS",
    "android.search.action.SEARCH_SETTINGS",
    "android.settings.DEVICE_INFO_SETTINGS",
    "android.settings.NFC_SETTINGS",
    "android.settings.NFCSHARING_SETTINGS",
    "android.settings.NFC_PAYMENT_SETTINGS",
    "android.settings.DREAM_SETTINGS",
    "android.settings.COMMUNAL_SETTINGS",
    "android.settings.NOTIFICATION_ASSISTANT_SETTINGS",
    "android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS",
    "android.settings.NOTIFICATION_LISTENER_DETAIL_SETTINGS",
    "android.settings.NOTIFICATION_POLICY_ACCESS_SETTINGS",
    "android.settings.NOTIFICATION_POLICY_ACCESS_DETAIL_SETTINGS",
    "android.settings.ACTION_CONDITION_PROVIDER_SETTINGS",
    "android.settings.CAPTIONING_SETTINGS",
    "android.settings.ACTION_PRINT_SETTINGS",
    "android.settings.ZEN_MODE_SETTINGS",
    "android.settings.ZEN_MODE_BLOCKED_EFFECTS_SETTINGS",
    "android.settings.ZEN_MODE_ONBOARDING",
    "android.settings.ZEN_MODE_PRIORITY_SETTINGS",
    "android.settings.ZEN_MODE_AUTOMATION_SETTINGS",
    "android.settings.VOICE_CONTROL_DO_NOT_DISTURB_MODE",
    "android.settings.ZEN_MODE_SCHEDULE_RULE_SETTINGS",
    "android.settings.ZEN_MODE_EVENT_RULE_SETTINGS",
    "android.settings.ZEN_MODE_EXTERNAL_RULE_SETTINGS",
    "android.settings.SHOW_REGULATORY_INFO",
    "android.settings.DEVICE_NAME",
    "android.settings.PAIRING_SETTINGS",
    "android.settings.BATTERY_SAVER_SETTINGS",
    "android.settings.VOICE_CONTROL_BATTERY_SAVER_MODE",
    "android.settings.HOME_SETTINGS",
    "android.settings.MANAGE_DEFAULT_APPS_SETTINGS",
    "android.settings.MANAGE_MORE_DEFAULT_APPS_SETTINGS",
    "android.settings.NOTIFICATION_SETTINGS",
    "android.settings.CONVERSATION_SETTINGS",
    "android.settings.NOTIFICATION_HISTORY",
    "android.settings.ALL_APPS_NOTIFICATION_SETTINGS",
    "android.settings.ALL_APPS_NOTIFICATION_SETTINGS_FOR_REVIEW",
    "android.settings.APP_NOTIFICATION_SETTINGS",
    "android.settings.CHANNEL_NOTIFICATION_SETTINGS",
    "android.settings.APP_NOTIFICATION_BUBBLE_SETTINGS",
    "android.settings.ACTION_APP_NOTIFICATION_REDACTION",
    "android.settings.ACTION_POWER_MENU_SETTINGS",
    "android.settings.ACTION_DEVICE_CONTROLS_SETTINGS",
    "android.settings.ACTION_MEDIA_CONTROLS_SETTINGS",
    "android.settings.SHOW_ADMIN_SUPPORT_DETAILS",
    "android.settings.MANAGE_SUPERVISOR_RESTRICTED_SETTING",
    "android.settings.SHOW_REMOTE_BUGREPORT_DIALOG",
    "android.settings.VR_LISTENER_SETTINGS",
    "android.settings.PICTURE_IN_PICTURE_SETTINGS",
    "android.settings.STORAGE_MANAGER_SETTINGS",
    "android.settings.WEBVIEW_SETTINGS",
    "android.settings.ENTERPRISE_PRIVACY_SETTINGS",
    "android.settings.SHOW_WORK_POLICY_INFO",
    "android.settings.REQUEST_SET_AUTOFILL_SERVICE",
    "android.settings.QUICK_ACCESS_WALLET_SETTINGS",
    "android.settings.STORAGE_VOLUME_ACCESS_SETTINGS",
    "android.settings.REQUEST_ENABLE_CONTENT_CAPTURE",
    "android.settings.MANAGE_DOMAIN_URLS",
    "android.settings.TETHER_SETTINGS",
    "com.android.settings.WIFI_TETHER_SETTINGS",
    "android.settings.ENABLE_MMS_DATA_REQUEST",
    "android.settings.SHOW_RESTRICTED_SETTING_DIALOG",
    "android.settings.extra.ENABLE_MMS_DATA_REQUEST_REASON",
    "android.settings.MMS_MESSAGE_SETTING",
    "android.settings.BEDTIME_SETTINGS");

fun humanSettingsName(s:String): String {
   val name= if(s.startsWith("android.settings.")){
          s.drop("android.settings.".length).lowercase().replace("_"," ")
    }else if(s.startsWith("com.android.settings.")){
          s.drop("com.android.settings.".length).lowercase().replace("_"," ")
    }else{
          s.lowercase().replace("_"," ")
    }

    return name.capitalizeWords()
}
fun String.capitalizeWords(): String {
    return this.split(" ")
        .joinToString(" ") { word ->
            word.replaceFirstChar {
                if (it.isLowerCase()) it.titlecase() else it.toString()
            }
        }
}
fun String.getLastName(): String {
    return this.split(".").lastOrNull() ?: this
}



fun String.capitalizeFirstLetter(): String {
    return this.replaceFirstChar { it.uppercase() }
}