package utils.table

object TableWidthCallLogs {
    val widths = mapOf(
        "No." to 50,
        "type" to 120,
        "number" to 150,
        "name" to 300,
        "date" to 170,
        "duration" to 60,
        "geocoded_location" to 60,
        "subject" to 40,
        "is_call_log_phone_account_migration_pending" to 50,
        "source_id" to 100,
        "my_number" to 120,
        "cloud_antispam_type" to 120,
        "subscription_id" to 100,
        "cloud_antispam_type_tag" to 120,
        "photo_id" to 80,
        "post_dial_digits" to 100,
        "call_screening_app_name" to 150,
        "priority" to 60,
        "countryiso" to 60,
        "forwarded_call" to 80,
        "sync_1" to 80,
        "sync_2" to 80,
        "sync_3" to 80,
        "photo_uri" to 150,
        "call_id_description" to 200,
        "missed_reason" to 120,
        "call_id_app_name" to 150,
        "block_reason" to 120,
        "subscription_component_name" to 150,
        "add_for_all_users" to 100,
        "numbertype" to 80,
        "features" to 80,
        "call_id_name" to 150,
        "transcription" to 200,
        "phone_call_type" to 100,
        "call_id_nuisance_confidence" to 120,
        "missed_count" to 60,
        "last_modified" to 120,
        "ai" to 60,
        "_id" to 60,
        "new" to 50,
        "simid" to 50,
        "contact_id" to 100,
        "presentation" to 80,
        "via_number" to 150,
        "number_type" to 80,
        "numberlabel" to 80,
        "normalized_number" to 150,
        "composer_photo_uri" to 150,
        "phone_account_address" to 150,
        "phone_account_hidden" to 100,
        "lookup_uri" to 150,
        "voicemail_uri" to 150,
        "matched_number" to 150,
        "call_id_package_name" to 150,
        "mark_deleted" to 80,
        "transcription_state" to 100,
        "data_usage" to 100,
        "location" to 100,
        "call_screening_component_name" to 150,
        "call_id_details" to 200,
        "is_read" to 60,
        "firewalltype" to 80
    )


}